version: '3'

services: 

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.prod
    image: edsontanaka/desafionodenginx:latest
    container_name: nginx
    networks: 
      - node-network-1
    ports: 
      - "8080:80"
    depends_on: 
      - app

  app:
    build: 
      context: node
    image: edsontanaka/desafionodeapp:latest
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    networks: 
      - node-network-1
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db

  db:
    build: 
      context: mysql
    image: edsontanaka/desafionodemysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network-1

networks: 
  node-network-1:
    driver: bridge      